title: nonadiabaticCoupling
description: This library contains the funcionality to compute an approximation to the nonadiabatic couping for a molecule.
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
